#ifndef NINJA_VERSION_H_
#define NINJA_VERSION_H_

#define NINJA_VERSION_MAJOR 3
#define NINJA_VERSION_MINOR 0
#define NINJA_VERSION_PATCH 0
#define NINJA_VERSION_STRING "3.0.0"
#define NINJA_SCM_VERSION "web"
#define NINJA_RELEASE_DATE "2025"

#endif /* NINJA_VERSION_H_ */
